# Enable or disable checkpointing
twister2.checkpointing.enable: false

# The implementation of the store to be used
#twister2.checkpointing.store: edu.iu.dsc.tws.checkpointing.stores.HDFSFileStateStore
twister2.checkpointing.store: edu.iu.dsc.tws.checkpointing.stores.LocalFileStateStore

# Root directory of local file system based store
twister2.checkpointing.store.fs.dir: "${TWISTER2_HOME}/persistent/"

# Root directory of hdfs based store
twister2.checkpointing.store.hdfs.dir: "/twister2/persistent/"

# Source triggering frequency
twister2.checkpointing.source.frequency: 1000
