# Enable or disable checkpointing
twister2.checkpointing.enable: false

# The implementation of the store to be used
#twister2.checkpointing.store: edu.iu.dsc.tws.checkpointing.stores.HDFSFileStateStore
twister2.checkpointing.store: edu.iu.dsc.tws.checkpointing.stores.LocalFileStateStore

# Root directory of local file system based store
twister2.checkpointing.store.fs.dir: "${TWISTER2_HOME}/persistent/"

# Root directory of hdfs based store
twister2.checkpointing.store.hdfs.dir: "/twister2/persistent/"

# Source triggering frequency
twister2.checkpointing.source.frequency: 1000

# Checkpointing message request timeout
twister2.checkpointing.request.timeout: 10000

###################################################################
# Fault Tolerance configurations
###################################################################

# a timeout value to determine whether a worker failed
# If a worker does not send heartbeat messages for this duration in milli seconds,
# It is assumed failed
twister2.fault.tolerance.failure.timeout: 10000

# maximum number of times to re-execute IWorker after some other workers failed in the job
# default value is 5
twister2.fault.tolerance.max.reexecutes: 5

# maximum number of times to re-start a worker from JVM
# default value is 5
twister2.fault.tolerance.max.worker.restarts: 5

# maximum number of times to re-start mpi jobs in case of failures
# default value is 3
twister2.fault.tolerance.max.mpijob.restarts: 1
